### ISSUE TITLE
make a new luarocks release

### ISSUE THREAD

**Issue by lipp** [brimworks/lua-ev#16]

**Comment by saucisson** [comment]
Yes, please, make a new luarocks release!

**Comment by mattbaker** [comment]
Ditto, hit this snag myself

**Comment by brimworks** [comment]
Sorry about this... I lost track of this issue, I'll plan to do a new release.

Thanks,
-Brian

**Comment by brimworks** [comment]
Okay, this is done.

Thanks,
-Brian

**Comment by mattbaker** [comment]
Thanks!

**Comment by lipp** [comment]
:100:
